---
title: "Untitled"
author: "Joe Nese"
date: "5/16/2019"
output: html_document
---

```{r setup, include=FALSE}
library(rio)
library(here)
library(tidyverse)
library(janitor)

knitr::opts_chunk$set(echo = TRUE)
```

# Wave 1
##2017-2018
```{r}

header_1_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-1.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q1, q2, q2_comments = q6, q3, q3_comments = q5, q7, q7_comments = q8, q9) %>%
  gather(label, question)

wave_1_1718 <- import(here::here("_posts", 
                                "2019-05-16-consequential-validity-teacher-surveys", 
                                "data", 
                                "2017-2018_wave-1.csv"))[-c(1:2), ] %>%
  clean_names() %>% 
  as_tibble() %>% 
  select(start_date, finished, q1, q2, q2_comments = q6, q3, q3_comments = q5, q7, q7_comments = q8, q9) %>% 
  group_by(q1) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q1) %>% 
  filter(order == 1) %>% 
  select(-order, -n) %>% 
  ungroup()


```

##2018-2019
```{r}
header_1_1819 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2018-2019_wave-1.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q1, q2, q2_comments = q6, q3, q3_comments = q5, q7, q7comments = q8, q9) %>%
  gather(label, question)

wave_1_1819 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2018-2019_wave-1.csv"))[-c(1, 2), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(finished, q1, q2, q2_comments = q6, q3, q3_comments = q5, q7, q7_comments = q8, q9 = q9_2)  %>% 
  group_by(q1) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q1) %>%  
  filter(finished == "True",
         q1 != "'@slane.k12.or.us") %>% 
  ungroup() %>% 
  group_by(q1) %>% 
  mutate(n2 = n()) %>% 
  mutate(keep = ifelse(n2 == 1, "keep", ifelse(n2 > 1 & order == 1, "keep", "toss"))) %>% 
  filter(keep == "keep") %>% 
  select(-order, -n, -n2, -keep) %>% 
  ungroup()
  
```

## Join
```{r}
wave_1 <- bind_rows(list("1718" = wave_1_1718, "1819" = wave_1_1819), .id = "year") %>% 
  mutate(q2 = recode(q2,
                    'Small groups (about how many per group)' = "Small groups",
                     'The entire class was tested together' = "Whole class"),
         q3 = recode(q3,
                     "Somewhat comfortable,Somewhat uncomfortable" = "Neutral"),
         q7 = recode(q7,
                     "No, I would prefer traditional oral reading fluency assessments." = "Traditional ORF",
                     "Yes, I would prefer the CORE system." = "CORE"))

header_1 <- header_1_1718 %>% 
  mutate(question = 
           case_when(
             label == "q1" ~ "email address",
             label == "q2" ~ "Did you have your students read in small groups, or was the entire class tested at the same time?",
             label == "q2_comments" ~ "Comments",
             label == "q3" ~ "How comfortable were your students with the assessment process (i.e., accessing the site, navigating the process, reading aloud with headsets, etc.)?",
             label == "q3_comments" ~ "Comments",
             label == "q7" ~ "Looking ahead, would you prefer traditional one-to-one ORF assessments or the CORE system as an alternative?",
             label == "q9" ~ "Comments or feedback about traditional ORF assessments",
             TRUE ~ as.character(question)
           )
  ) %>% 
  spread(label, question)

export(wave_1, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "wave_1.csv"))

export(header_1, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "header_1.csv"))
```



# Wave 2

## 2017-2018

```{r}
header_2_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-2.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q11, q2, q2_comments = q6, q7, q7_comments = q8, q10, q10_comments = q12, q9) %>%
  gather(label, question)

wave_2_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-2.csv"))[-c(1, 2), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(start_date, finished, q11, q2, q2_comments = q6, q7, q7_comments = q8, q10, q10_comments = q12, q9) %>% 
  group_by(q11) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q11) %>%  
  filter(order == 1,
         finished == "True",
         q11 != "asdf") %>% 
  select(-order, -n) %>% 
  ungroup()


```

## 2018-2019
```{r}
header_2_1819 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2018-2019_wave-2.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q11, q2, q2_comments = q6, q7, q7_comments = q8, q13, q13_comments = q14, q10, q10_comments = q12, q9) %>%
  gather(label, question)

wave_2_1819 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2018-2019_wave-2.csv"))[-c(1, 2), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(start_date, finished, q11, q2, q2_comments = q6, q7, q7_comments = q8, q13, q13_comments = q14, q10, q10_comments = q12, q9) %>% 
  group_by(q11) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q11) %>%
  filter(finished == "True") %>% 
  mutate(keep = 
           case_when(
             n == 1 ~ "keep",
             q11 == "mpoland@sheltonschools.org" & order == 2 ~ "keep",
             q11 == "adam.fine@springfield.k12.or.us" & order == 2 ~ "keep",
             q11 == "mpoland@sheltonschools.org" | q11 == "adam.fine@springfield.k12.or.us" & order == 1 ~ "toss",
             n > 1 & order == 1  ~ "keep",
             TRUE ~ "toss")) %>%
  filter(keep == "keep") %>% 
  select(-order, -n, -keep) %>% 
  ungroup()
	
```

## Join
```{r}
wave_2 <- bind_rows(list("1718" = wave_2_1718, "1819" = wave_2_1819), .id = "year")

header_2 <- header_2_1819 %>% 
  mutate(question = 
           case_when(
             label == "q11" ~ "email address",
             label == "q2" ~ "Are ORF scores valuable for your teaching?",
             label == "q2_comments" ~ "Comments",
             label == "q7" ~ "Do you administer all the traditional ORF one-to-one ORF benchmark assessments to students in your classroom?",
             label == "q7_comments" ~ "Comments",
             label == "q13" ~ "Do you administer all the traditional ORF one-to-one ORF progress monitoring assessments to students in your classroom?",
             label == "q13_comments" ~ "Comments",
             label == "q9" ~ "Comments or feedback about traditional ORF assessments",
             TRUE ~ as.character(question)
           )
  ) %>% 
  spread(label, question)

export(wave_2, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "wave_2.csv"))

export(header_2, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "header_2.csv"))
```

# Wave 3

## 2017-2018
```{r}
header_3_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-3.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q11, q10) %>%
  gather(label, question)

wave_3_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-3.csv"))[-c(1, 2), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(start_date, finished, q11, q10) %>% 
  group_by(q11) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q11) %>% 
  filter(finished == "True",
         q11 != ".",
         order == 1) %>% 
  select(-order, -n)
```

##2018-2019
```{r}
header_3_1819 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2018-2019_wave-3.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q11, q10) %>%
  gather(label, question)

wave_3_1819 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2018-2019_wave-3.csv"))[-c(1, 2), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(start_date, finished, q11, q10) %>% 
  group_by(q11) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q11) %>%
  filter(order == 1,
         q11 != ".",
         q11 != "springfield") %>%  
  select(-order, -n)
```

## Join
```{r}
wave_3 <- bind_rows(list("1718" = wave_3_1718, "1819" = wave_3_1819), .id = "year")

header_3 <- header_3_1819 %>% 
  mutate(question = 
           case_when(
             label == "q11" ~ "email address",
             label == "q10" ~ "How would you improve traditional ORF assessment, and/or what are some of the barriers you experience with these assessments?",
             TRUE ~ as.character(question)
           )
  ) %>% 
  spread(label, question)

export(wave_3, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "wave_3.csv"))

export(header_3, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "header_3.csv"))
```

# Wave 4

## 2017-2018
```{r}
header_4_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-4.csv"))[c(1), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(q11, q13) %>%
  gather(label, question)

wave_4_1718 <- import(here::here("_posts", 
                                   "2019-05-16-consequential-validity-teacher-surveys", 
                                   "data", 
                                   "2017-2018_wave-4.csv"))[-c(1, 2), ] %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(start_date, finished, q11, q13) %>% 
  group_by(q11) %>% 
  mutate(order = row_number(),
         n = n()) %>% 
  arrange(-n, q11) %>% 
  filter(finished == "True",
         q11 != "Shelton",
         order == 1) %>% 
  select(-order, -n)

```

## 2018-2019

################################---------------------- DO THIS!
```{r}

```



## Join
```{r}


header_4 <- header_4_1718 %>% 
  mutate(question = 
           case_when(
             label == "q11" ~ "email address",
             label == "q13" ~ "Thinking about your experience during this study, and the experiences of your students, how could the study be improved for teachers?",
             TRUE ~ as.character(question)
           )
  ) %>% 
  spread(label, question)

export(header_4, here::here("_posts", 
                          "2019-05-16-consequential-validity-teacher-surveys", 
                          "data", 
                          "header_4.csv"))
```

